# version format
version: "{build}"

image: Visual Studio 2015
platform: x64
configuration: release

clone_folder: C:\projects\ants-windows

environment:
  ANTSSRC: C:\projects\deps\ANTs
  ANTSBUILD: C:\projects\deps\antsbin

install:
  - nuget install zlib-msvc14-x64-master -Version 1.2.8.4 -Source https://ci.appveyor.com/nuget/zlib-shallow-x0n34b3pfq1b
  - set ZLIB_DIR="C:\projects\ants-windows\zlib-msvc14-x64-master.1.2.8.4"
  - IF NOT EXIST C:\projects\deps mkdir C:\projects\deps
  - cd C:\projects\deps
  - set ANTS_URL="https://github.com/ANTsX/ANTs.git"
  - IF NOT EXIST %ANTSSRC% (
    git clone -b v2.2.0 %ANTS_URL%
    )
  - IF NOT EXIST %ANTSBUILD% (
     mkdir %ANTSBUILD% &&
     cd %ANTSBUILD% &&
     cmake -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND" -DCMAKE_BUILD_TYPE=Release -DZLIB_INCLUDE_DIR=%ZLIB_DIR% -DZLIB_LIBRARY=%ZLIB_DIR%\zlib.lib ..\ANTs &&
     dir C:\projects\deps\antsbin &&
     mingw32-make
     )

cache:
  - C:\projects\deps\ANTs
  - C:\projects\deps\antsbin -> appveyor.yml

build_script:
  - cd C:\projects\ants-windows
